package josecarlos.analizadorlexico.paneles;

import josecarlos.analizadorlexico.tokens.Token;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;
import josecarlos.analizadorlexico.AnalizadorLexico;

/**
 *
 * @author emahch
 */
public class PanelCodigo extends javax.swing.JPanel {

    private AnalizadorLexico analizador;
    private PanelImagen panelImagen;
    private List<Token> tokens;
    
    /**
     * Creates new form PanelCodigo
     * @param panelImagen
     */
    public PanelCodigo(PanelImagen panelImagen) {
        this.panelImagen = panelImagen;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPosicionTexto = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        labelTituloPosicionTexto = new javax.swing.JLabel();
        labelLimiteExcedido = new javax.swing.JLabel();

        labelPosicionTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicionTexto.setText("Linea: X, Columna: X");

        scrollPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setColumns(20);
        txtCodigo.setFont(new java.awt.Font("Nimbus Mono PS", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setLineWrap(true);
        txtCodigo.setRows(5);
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodigoCaretUpdate(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        scrollPanel.setViewportView(txtCodigo);

        labelTituloPosicionTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloPosicionTexto.setText("Posicion");

        labelLimiteExcedido.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelLimiteExcedido.setForeground(new java.awt.Color(153, 0, 0));
        labelLimiteExcedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLimiteExcedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(labelTituloPosicionTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(labelPosicionTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLimiteExcedido)
                .addGap(1, 1, 1)
                .addComponent(labelTituloPosicionTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPosicionTexto))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodigoCaretUpdate
        int linea = 1;
        int columna = 1;
        try {
            int caretpos = txtCodigo.getCaretPosition();

            linea = txtCodigo.getLineOfOffset(caretpos);
            columna = caretpos - txtCodigo.getLineStartOffset(linea);
            linea += 1;
        } catch (BadLocationException ex) {
        }
        actualizarEstado(linea, columna);
    }//GEN-LAST:event_txtCodigoCaretUpdate

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyReleased

    public List<Token> getTokens(){
        return tokens;
    }
    
    public void analizarTexto(){
        analizador = new AnalizadorLexico(txtCodigo.getText());
        tokens = analizador.generarTokens();
        panelImagen.generarCuadricula(tokens);
        if (tokens.size() > panelImagen.getDimensionCuadricula().height*panelImagen.getDimensionCuadricula().width) {
            labelLimiteExcedido.setText("Limite de tokens superado");
        } else {
            labelLimiteExcedido.setText("");
        }
    }
    
    private void actualizarEstado(int fila, int columna) {
        labelPosicionTexto.setText("Fila: " + fila + ", Columna: " + columna);
        analizarTexto();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelLimiteExcedido;
    private javax.swing.JLabel labelPosicionTexto;
    private javax.swing.JLabel labelTituloPosicionTexto;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTextArea txtCodigo;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabelPosicionTexto() {
        return labelPosicionTexto;
    }

    public JTextArea getTxtCodigo() {
        return txtCodigo;
    }
}
