package josecarlos.analizadorlexico;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author emahch
 */
public class FramePrincipal extends javax.swing.JFrame {

    private boolean botonesActivos = true;
    private PanelContenido panelContenido;
    private Dimension dimensionImagen;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        togleBotones();
        solicitarCuadricula();
        
        panelContenido = new PanelContenido(dimensionImagen);
        getContentPane().add(panelContenido, BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelAcciones = new javax.swing.JPanel();
        botonIngresarArchivo = new javax.swing.JButton();
        botonExportarPng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Léxico");
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cambios Guardados");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_END);

        botonIngresarArchivo.setBackground(new java.awt.Color(0, 102, 153));
        botonIngresarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresarArchivo.setText("Ingresar Archivo");
        botonIngresarArchivo.setFocusPainted(false);
        botonIngresarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarArchivoActionPerformed(evt);
            }
        });
        panelAcciones.add(botonIngresarArchivo);

        botonExportarPng.setBackground(new java.awt.Color(0, 102, 153));
        botonExportarPng.setForeground(new java.awt.Color(255, 255, 255));
        botonExportarPng.setText("Exportar Imágen");
        botonExportarPng.setFocusPainted(false);
        panelAcciones.add(botonExportarPng);

        getContentPane().add(panelAcciones, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void togleBotones() {
        botonesActivos = !botonesActivos;
        botonIngresarArchivo.setEnabled(botonesActivos);
        botonExportarPng.setEnabled(botonesActivos);
    }
    
    private void solicitarCuadricula() {
        DialogSolicitarCuadricula dialogCuadricula = new DialogSolicitarCuadricula(this);
        dialogCuadricula.setVisible(true);
        if (dialogCuadricula.getConfirmacion()) {
            dimensionImagen = dialogCuadricula.getDimension();
            togleBotones();
        } else {
            System.exit(0);
        }
    }

    private void botonIngresarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarArchivoActionPerformed
        try {
            JTextArea txtCodigo = panelContenido.getPanelCodigo().getTxtCodigo();
            
            ExportImportFiles importArchivo = new ExportImportFiles(false);
            String texto = importArchivo.recibirArchivoEntrada();
            txtCodigo.setText(texto);
        } catch (SolicitudCanceladaException ex) {
        }
    }//GEN-LAST:event_botonIngresarArchivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExportarPng;
    private javax.swing.JButton botonIngresarArchivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelAcciones;
    // End of variables declaration//GEN-END:variables
}
