package josecarlos.analizadorlexico;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/**
 *
 * @author emahch
 */
public class PanelCodigo extends javax.swing.JPanel {


    /**
     * Creates new form PanelCodigo
     */
    public PanelCodigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPosicionTexto = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        labelPosicionImagen = new javax.swing.JLabel();

        labelPosicionTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicionTexto.setText("Columnas: X, Filas: Y");

        scrollPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setColumns(20);
        txtCodigo.setFont(new java.awt.Font("Nimbus Mono L", 0, 15)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setLineWrap(true);
        txtCodigo.setRows(5);
        txtCodigo.setText("PRUEBA");
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodigoCaretUpdate(evt);
            }
        });
        scrollPanel.setViewportView(txtCodigo);

        labelPosicionImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicionImagen.setText("Columnas: X, Filas: Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPosicionTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPosicionImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                    .addComponent(scrollPanel))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosicionTexto)
                    .addComponent(labelPosicionImagen))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodigoCaretUpdate
        int linea = 1;
        int columna = 1;

        try {
            int caretpos = txtCodigo.getCaretPosition();
            
            linea = txtCodigo.getLineOfOffset(caretpos);
            columna = caretpos - txtCodigo.getLineStartOffset(linea);

            // Ya que las líneas las cuenta desde la 0
            linea += 1;
        } catch (BadLocationException ex) {
        }

        // Actualizamos el estado
        actualizarEstado(linea, columna);
    }//GEN-LAST:event_txtCodigoCaretUpdate

    private void actualizarEstado(int linea, int columna) {
        labelPosicionTexto.setText("Linea: " + linea + " Columna: " + columna);
        try {
            txtCodigo.getDocument().getText(0, 1);
            labelPosicionImagen.setText(txtCodigo.getDocument().getText(0, 2));
        } catch (BadLocationException ex) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPosicionImagen;
    private javax.swing.JLabel labelPosicionTexto;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTextArea txtCodigo;
    // End of variables declaration//GEN-END:variables
}
